system:
  mode: "MOCK"               # Change to "LIVE" when ESP32 is connected
  check_interval: 1        # Seconds between checks

thresholds:
  leak_variance: 0.5         # Variance limit for leak detection
  night_start: 23            # 11 PM
  night_end: 5               # 5 AM

telegram:
  bot_token: "8503985725:AAHhCLZmMqEfTreaJSGLLQonPFk11goCkYc"  # Paste your token from BotFather
  subscribers:
    - "8454691802"            # You